// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package ip575

// ExpBySqrtPp1o4 is equivalent to z.Exp(x, 116000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000).
// It raises x to the (p+1)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPp1o4(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_100      = 1 + _11
	//	_1000000  = _100 << 4
	//	_1000100  = _100 + _1000000
	//	_10001000 = 2*_1000100
	//	_10001011 = _11 + _10001000
	//	return      _10001011 << 565
	//
	// Operations: 571 squares 4 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
	)

	// var t0,t1 Element
	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: t0 = x^0x4
	t0.Mul(&x, z)

	// Step 7: t1 = x^0x40
	t1.Square(t0)
	for s := 1; s < 4; s++ {
		t1.Square(t1)
	}

	// Step 8: t0 = x^0x44
	t0.Mul(t0, t1)

	// Step 9: t0 = x^0x88
	t0.Square(t0)

	// Step 10: z = x^0x8b
	z.Mul(z, t0)

	// Step 575: z = x^0x116000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	for s := 0; s < 565; s++ {
		z.Square(z)
	}

	return z
}

// ExpBySqrtPm3o4 is equivalent to z.Exp(x, 115fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff).
// It raises x to the (p-3)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPm3o4(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_11      = 1 + _10
	//	_101     = _10 + _11
	//	_1000    = _11 + _101
	//	_1010    = _10 + _1000
	//	_10100   = 2*_1010
	//	_10101   = 1 + _10100
	//	_11101   = _1000 + _10101
	//	_100010  = _101 + _11101
	//	_111111  = _11101 + _100010
	//	_1111110 = 2*_111111
	//	_1111111 = 1 + _1111110
	//	i17      = _1111111 << 5
	//	i18      = _1010 + i17
	//	i25      = i17 << 7
	//	i26      = i18 + i25
	//	i33      = i25 << 7
	//	i34      = i26 + i33
	//	i41      = i33 << 7
	//	i42      = i34 + i41
	//	i49      = i41 << 7
	//	i50      = i42 + i49
	//	i57      = i49 << 7
	//	i58      = i50 + i57
	//	i66      = i57 << 7 + i58
	//	x54      = _10101 + i66
	//	x61      = x54 << 7 + _1111111
	//	i130     = x61 << 54 + i66
	//	i131     = _100010 + i130
	//	i132     = i130 + i131
	//	i135     = 2*(i131 + i132) + 1
	//	i136     = i132 + i135
	//	i141     = (i135 + i136) << 3 + _11
	//	i142     = i136 + i141
	//	i143     = i141 + i142
	//	i146     = 2*(i142 + i143) + 1
	//	i149     = (i143 + i146) << 2
	//	x128     = i146 + i149 + i149
	//	i409     = ((i146 + x128) << 127 + x128) << 128 + x128
	//	return     (i409 << 128 + x128) << 61 + x61
	//
	// Operations: 562 squares 38 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
		t3 = new(Element)
		t4 = new(Element)
	)

	// var t0,t1,t2,t3,t4 Element
	// Step 1: t1 = x^0x2
	t1.Square(&x)

	// Step 2: t0 = x^0x3
	t0.Mul(&x, t1)

	// Step 3: t2 = x^0x5
	t2.Mul(t1, t0)

	// Step 4: z = x^0x8
	z.Mul(t0, t2)

	// Step 5: t1 = x^0xa
	t1.Mul(t1, z)

	// Step 6: t3 = x^0x14
	t3.Square(t1)

	// Step 7: t3 = x^0x15
	t3.Mul(&x, t3)

	// Step 8: z = x^0x1d
	z.Mul(z, t3)

	// Step 9: t2 = x^0x22
	t2.Mul(t2, z)

	// Step 10: z = x^0x3f
	z.Mul(z, t2)

	// Step 11: z = x^0x7e
	z.Square(z)

	// Step 12: z = x^0x7f
	z.Mul(&x, z)

	// Step 17: t4 = x^0xfe0
	t4.Square(z)
	for s := 1; s < 5; s++ {
		t4.Square(t4)
	}

	// Step 18: t1 = x^0xfea
	t1.Mul(t1, t4)

	// Step 25: t4 = x^0x7f000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 26: t1 = x^0x7ffea
	t1.Mul(t1, t4)

	// Step 33: t4 = x^0x3f80000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 34: t1 = x^0x3ffffea
	t1.Mul(t1, t4)

	// Step 41: t4 = x^0x1fc000000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 42: t1 = x^0x1ffffffea
	t1.Mul(t1, t4)

	// Step 49: t4 = x^0xfe00000000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 50: t1 = x^0xffffffffea
	t1.Mul(t1, t4)

	// Step 57: t4 = x^0x7f0000000000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 58: t1 = x^0x7fffffffffea
	t1.Mul(t1, t4)

	// Step 65: t4 = x^0x3f800000000000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 66: t1 = x^0x3fffffffffffea
	t1.Mul(t1, t4)

	// Step 67: t3 = x^0x3fffffffffffff
	t3.Mul(t3, t1)

	// Step 74: t3 = x^0x1fffffffffffff80
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}

	// Step 75: z = x^0x1fffffffffffffff
	z.Mul(z, t3)

	// Step 129: t3 = x^0x7ffffffffffffffc0000000000000
	t3.Square(z)
	for s := 1; s < 54; s++ {
		t3.Square(t3)
	}

	// Step 130: t1 = x^0x7ffffffffffffffffffffffffffea
	t1.Mul(t1, t3)

	// Step 131: t2 = x^0x8000000000000000000000000000c
	t2.Mul(t2, t1)

	// Step 132: t1 = x^0xffffffffffffffffffffffffffff6
	t1.Mul(t1, t2)

	// Step 133: t2 = x^0x180000000000000000000000000002
	t2.Mul(t2, t1)

	// Step 134: t2 = x^0x300000000000000000000000000004
	t2.Square(t2)

	// Step 135: t2 = x^0x300000000000000000000000000005
	t2.Mul(&x, t2)

	// Step 136: t1 = x^0x3ffffffffffffffffffffffffffffb
	t1.Mul(t1, t2)

	// Step 137: t2 = x^0x700000000000000000000000000000
	t2.Mul(t2, t1)

	// Step 140: t2 = x^0x3800000000000000000000000000000
	for s := 0; s < 3; s++ {
		t2.Square(t2)
	}

	// Step 141: t0 = x^0x3800000000000000000000000000003
	t0.Mul(t0, t2)

	// Step 142: t1 = x^0x3bffffffffffffffffffffffffffffe
	t1.Mul(t1, t0)

	// Step 143: t0 = x^0x7400000000000000000000000000001
	t0.Mul(t0, t1)

	// Step 144: t1 = x^0xaffffffffffffffffffffffffffffff
	t1.Mul(t1, t0)

	// Step 145: t1 = x^0x15fffffffffffffffffffffffffffffe
	t1.Square(t1)

	// Step 146: t1 = x^0x15ffffffffffffffffffffffffffffff
	t1.Mul(&x, t1)

	// Step 147: t0 = x^0x1d400000000000000000000000000000
	t0.Mul(t0, t1)

	// Step 149: t0 = x^0x75000000000000000000000000000000
	for s := 0; s < 2; s++ {
		t0.Square(t0)
	}

	// Step 150: t2 = x^0x8affffffffffffffffffffffffffffff
	t2.Mul(t1, t0)

	// Step 151: t0 = x^0xffffffffffffffffffffffffffffffff
	t0.Mul(t0, t2)

	// Step 152: t1 = x^0x115fffffffffffffffffffffffffffffe
	t1.Mul(t1, t0)

	// Step 279: t1 = x^0x8affffffffffffffffffffffffffffff00000000000000000000000000000000
	for s := 0; s < 127; s++ {
		t1.Square(t1)
	}

	// Step 280: t1 = x^0x8affffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 408: t1 = x^0x8affffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000
	for s := 0; s < 128; s++ {
		t1.Square(t1)
	}

	// Step 409: t1 = x^0x8affffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 537: t1 = x^0x8affffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000
	for s := 0; s < 128; s++ {
		t1.Square(t1)
	}

	// Step 538: t0 = x^0x8affffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(t0, t1)

	// Step 599: t0 = x^0x115fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe000000000000000
	for s := 0; s < 61; s++ {
		t0.Square(t0)
	}

	// Step 600: z = x^0x115fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, t0)

	return z
}

// ExpByCbrt2QPlus1Div9 is equivalent to z.Exp(x, f71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7).
// It raises x to the (2q+1)/9 power using a shorter addition chain.
// This is used when q ≡ 4 (mod 9) for efficient cube root computation.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrt2QPlus1Div9(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_100      = 2*_10
	//	_101      = 1 + _100
	//	_111      = _10 + _101
	//	_1000     = 1 + _111
	//	_1101     = _101 + _1000
	//	_1101000  = _1101 << 3
	//	_1110000  = _1000 + _1101000
	//	_11100000 = 2*_1110000
	//	i12       = 2*_11100000
	//	i26       = (i12 << 5 + _11100000) << 7 + i12
	//	i53       = (i26 << 5 + _11100000) << 19 + i26 + _111
	//	i64       = i53 << 10 + _1110000
	//	i69       = 2*(2*i64 + i64) + i64 + _1101
	//	i72       = 2*i69 + i69 + i64
	//	i76       = i72 << 2 + i72 + i69
	//	i78       = i72 + i76 + i76
	//	i212      = ((i72 + i78) << 65 + i78) << 66 + i78
	//	i412      = ((i212 << 66 + i78) << 66 + i78) << 66
	//	i547      = ((i78 + i412) << 66 + i78) << 66 + i78
	//	return      i547 << 48 + i53
	//
	// Operations: 567 squares 29 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
		t3 = new(Element)
		t4 = new(Element)
	)

	// var t0,t1,t2,t3,t4 Element
	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t0 = x^0x4
	t0.Square(z)

	// Step 3: t0 = x^0x5
	t0.Mul(&x, t0)

	// Step 4: z = x^0x7
	z.Mul(z, t0)

	// Step 5: t1 = x^0x8
	t1.Mul(&x, z)

	// Step 6: t0 = x^0xd
	t0.Mul(t0, t1)

	// Step 9: t2 = x^0x68
	t2.Square(t0)
	for s := 1; s < 3; s++ {
		t2.Square(t2)
	}

	// Step 10: t1 = x^0x70
	t1.Mul(t1, t2)

	// Step 11: t3 = x^0xe0
	t3.Square(t1)

	// Step 12: t2 = x^0x1c0
	t2.Square(t3)

	// Step 17: t4 = x^0x3800
	t4.Square(t2)
	for s := 1; s < 5; s++ {
		t4.Square(t4)
	}

	// Step 18: t4 = x^0x38e0
	t4.Mul(t3, t4)

	// Step 25: t4 = x^0x1c7000
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 26: t2 = x^0x1c71c0
	t2.Mul(t2, t4)

	// Step 31: t4 = x^0x38e3800
	t4.Square(t2)
	for s := 1; s < 5; s++ {
		t4.Square(t4)
	}

	// Step 32: t3 = x^0x38e38e0
	t3.Mul(t3, t4)

	// Step 51: t3 = x^0x1c71c7000000
	for s := 0; s < 19; s++ {
		t3.Square(t3)
	}

	// Step 52: t2 = x^0x1c71c71c71c0
	t2.Mul(t2, t3)

	// Step 53: z = x^0x1c71c71c71c7
	z.Mul(z, t2)

	// Step 63: t2 = x^0x71c71c71c71c00
	t2.Square(z)
	for s := 1; s < 10; s++ {
		t2.Square(t2)
	}

	// Step 64: t1 = x^0x71c71c71c71c70
	t1.Mul(t1, t2)

	// Step 65: t2 = x^0xe38e38e38e38e0
	t2.Square(t1)

	// Step 66: t2 = x^0x155555555555550
	t2.Mul(t1, t2)

	// Step 67: t2 = x^0x2aaaaaaaaaaaaa0
	t2.Square(t2)

	// Step 68: t2 = x^0x31c71c71c71c710
	t2.Mul(t1, t2)

	// Step 69: t0 = x^0x31c71c71c71c71d
	t0.Mul(t0, t2)

	// Step 70: t2 = x^0x638e38e38e38e3a
	t2.Square(t0)

	// Step 71: t2 = x^0x955555555555557
	t2.Mul(t0, t2)

	// Step 72: t1 = x^0x9c71c71c71c71c7
	t1.Mul(t1, t2)

	// Step 74: t2 = x^0x271c71c71c71c71c
	t2.Square(t1)
	for s := 1; s < 2; s++ {
		t2.Square(t2)
	}

	// Step 75: t2 = x^0x30e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 76: t0 = x^0x3400000000000000
	t0.Mul(t0, t2)

	// Step 77: t2 = x^0x3dc71c71c71c71c7
	t2.Mul(t1, t0)

	// Step 78: t0 = x^0x71c71c71c71c71c7
	t0.Mul(t0, t2)

	// Step 79: t1 = x^0x7b8e38e38e38e38e
	t1.Mul(t1, t0)

	// Step 144: t1 = x^0xf71c71c71c71c71c0000000000000000
	for s := 0; s < 65; s++ {
		t1.Square(t1)
	}

	// Step 145: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 211: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 212: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 278: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 279: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 345: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 346: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 412: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 413: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 479: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 480: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t0, t1)

	// Step 546: t1 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for s := 0; s < 66; s++ {
		t1.Square(t1)
	}

	// Step 547: t0 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t0.Mul(t0, t1)

	// Step 595: t0 = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7000000000000
	for s := 0; s < 48; s++ {
		t0.Square(t0)
	}

	// Step 596: z = x^0xf71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	z.Mul(z, t0)

	return z
}

// ExpByCbrtHelperQMinus4Div9 is equivalent to z.Exp(x, 7b8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3).
// It raises x to the (q-4)/9 power using an addition chain.
// This helper is used by cbrtAndNormInverse to share exponentiation between
// cube root and norm inverse computations.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrtHelperQMinus4Div9(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_100    = 1 + _11
	//	_111    = _11 + _100
	//	_1011   = _100 + _111
	//	_1110   = _11 + _1011
	//	_11001  = _1011 + _1110
	//	_11100  = _11 + _11001
	//	_110101 = _11001 + _11100
	//	_111000 = _11 + _110101
	//	i17     = _111000 << 6 + _110101
	//	i21     = (_11 + i17) << 3
	//	i22     = _111 + i21
	//	i34     = i21 << 12
	//	i35     = i22 + i34
	//	i47     = i34 << 12
	//	i48     = i35 + i47
	//	i61     = i47 << 12 + i48
	//	i62     = 2*i61
	//	i63     = i61 + i62
	//	i64     = i62 + i63
	//	i77     = (i63 + i64) << 12
	//	i78     = i17 + i77
	//	i133    = i77 << 54 + i78
	//	i134    = _100 + i133
	//	i135    = _11 + i134
	//	i137    = 2*(i133 + i135)
	//	i138    = i134 + i137
	//	i139    = i135 + i138
	//	i141    = 2*(i138 + i139)
	//	i142    = i137 + i141
	//	i143    = i139 + i142
	//	i144    = i141 + i142
	//	i145    = i143 + i144
	//	i148    = 2*(i144 + i145) + 1
	//	i409    = ((i141 + i148) << 131 + i148) << 127 + i145
	//	return    (i409 << 131 + i148) << 54 + i64
	//
	// Operations: 559 squares 37 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
		t3 = new(Element)
	)

	// var t0,t1,t2,t3 Element
	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t1 = x^0x3
	t1.Mul(&x, z)

	// Step 3: t2 = x^0x4
	t2.Mul(&x, t1)

	// Step 4: z = x^0x7
	z.Mul(t1, t2)

	// Step 5: t0 = x^0xb
	t0.Mul(t2, z)

	// Step 6: t3 = x^0xe
	t3.Mul(t1, t0)

	// Step 7: t0 = x^0x19
	t0.Mul(t0, t3)

	// Step 8: t3 = x^0x1c
	t3.Mul(t1, t0)

	// Step 9: t0 = x^0x35
	t0.Mul(t0, t3)

	// Step 10: t3 = x^0x38
	t3.Mul(t1, t0)

	// Step 16: t3 = x^0xe00
	for s := 0; s < 6; s++ {
		t3.Square(t3)
	}

	// Step 17: t0 = x^0xe35
	t0.Mul(t0, t3)

	// Step 18: t3 = x^0xe38
	t3.Mul(t1, t0)

	// Step 21: t3 = x^0x71c0
	for s := 0; s < 3; s++ {
		t3.Square(t3)
	}

	// Step 22: z = x^0x71c7
	z.Mul(z, t3)

	// Step 34: t3 = x^0x71c0000
	for s := 0; s < 12; s++ {
		t3.Square(t3)
	}

	// Step 35: z = x^0x71c71c7
	z.Mul(z, t3)

	// Step 47: t3 = x^0x71c0000000
	for s := 0; s < 12; s++ {
		t3.Square(t3)
	}

	// Step 48: z = x^0x71c71c71c7
	z.Mul(z, t3)

	// Step 60: t3 = x^0x71c0000000000
	for s := 0; s < 12; s++ {
		t3.Square(t3)
	}

	// Step 61: t3 = x^0x71c71c71c71c7
	t3.Mul(z, t3)

	// Step 62: z = x^0xe38e38e38e38e
	z.Square(t3)

	// Step 63: t3 = x^0x15555555555555
	t3.Mul(t3, z)

	// Step 64: z = x^0x238e38e38e38e3
	z.Mul(z, t3)

	// Step 65: t3 = x^0x38e38e38e38e38
	t3.Mul(t3, z)

	// Step 77: t3 = x^0x38e38e38e38e38000
	for s := 0; s < 12; s++ {
		t3.Square(t3)
	}

	// Step 78: t0 = x^0x38e38e38e38e38e35
	t0.Mul(t0, t3)

	// Step 132: t3 = x^0xe38e38e38e38e00000000000000000
	for s := 0; s < 54; s++ {
		t3.Square(t3)
	}

	// Step 133: t0 = x^0xe38e38e38e38e38e38e38e38e38e35
	t0.Mul(t0, t3)

	// Step 134: t2 = x^0xe38e38e38e38e38e38e38e38e38e39
	t2.Mul(t2, t0)

	// Step 135: t1 = x^0xe38e38e38e38e38e38e38e38e38e3c
	t1.Mul(t1, t2)

	// Step 136: t0 = x^0x1c71c71c71c71c71c71c71c71c71c71
	t0.Mul(t0, t1)

	// Step 137: t0 = x^0x38e38e38e38e38e38e38e38e38e38e2
	t0.Square(t0)

	// Step 138: t2 = x^0x471c71c71c71c71c71c71c71c71c71b
	t2.Mul(t2, t0)

	// Step 139: t1 = x^0x5555555555555555555555555555557
	t1.Mul(t1, t2)

	// Step 140: t2 = x^0x9c71c71c71c71c71c71c71c71c71c72
	t2.Mul(t2, t1)

	// Step 141: t2 = x^0x138e38e38e38e38e38e38e38e38e38e4
	t2.Square(t2)

	// Step 142: t0 = x^0x171c71c71c71c71c71c71c71c71c71c6
	t0.Mul(t0, t2)

	// Step 143: t1 = x^0x1c71c71c71c71c71c71c71c71c71c71d
	t1.Mul(t1, t0)

	// Step 144: t0 = x^0x2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
	t0.Mul(t2, t0)

	// Step 145: t1 = x^0x471c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t1, t0)

	// Step 146: t0 = x^0x71c71c71c71c71c71c71c71c71c71c71
	t0.Mul(t0, t1)

	// Step 147: t0 = x^0xe38e38e38e38e38e38e38e38e38e38e2
	t0.Square(t0)

	// Step 148: t0 = x^0xe38e38e38e38e38e38e38e38e38e38e3
	t0.Mul(&x, t0)

	// Step 149: t2 = x^0xf71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t2, t0)

	// Step 280: t2 = x^0x7b8e38e38e38e38e38e38e38e38e38e3800000000000000000000000000000000
	for s := 0; s < 131; s++ {
		t2.Square(t2)
	}

	// Step 281: t2 = x^0x7b8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t0, t2)

	// Step 408: t2 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000000000000000000000000000
	for s := 0; s < 127; s++ {
		t2.Square(t2)
	}

	// Step 409: t1 = x^0x3dc71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(t1, t2)

	// Step 540: t1 = x^0x1ee38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3800000000000000000000000000000000
	for s := 0; s < 131; s++ {
		t1.Square(t1)
	}

	// Step 541: t0 = x^0x1ee38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t0.Mul(t0, t1)

	// Step 595: t0 = x^0x7b8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38c0000000000000
	for s := 0; s < 54; s++ {
		t0.Square(t0)
	}

	// Step 596: z = x^0x7b8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	z.Mul(z, t0)

	return z
}
