// Code generated by internal/generator/cbrt. DO NOT EDIT.
package ip765

// nSquare repeated squaring: z = x^(2^n).
func (z *E2) nSquare(x *E2, n int) *E2 {
	z.Square(x)
	for i := 1; i < n; i++ {
		z.Square(z)
	}
	return z
}

// expByE2Cbrt is equivalent to z.Exp(x, 0x1caac71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c38aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab).
// It uses an addition chain generated by github.com/mmcloughlin/addchain.
//
// Operations: 1511 squares 75 multiplies
func (z *E2) expByE2Cbrt(x E2) *E2 {
	var (
		t0 E2
		t1 E2
		t2 E2
		t3 E2
		t4 E2
		t5 E2
		t6 E2
		t7 E2
		t8 E2
	)

	z.Square(&x)
	t1.Mul(&x, z)
	t2.Square(&t1)
	t6.Mul(&x, &t2)
	t5.Square(&t2)
	t0.Mul(&x, &t5)
	t3.Mul(&x, &t0)
	t0.Mul(&t0, &t3)
	t4.Mul(z, &t0)
	z.Mul(&t1, &t4)
	t2.Mul(&t2, z)
	t4.Mul(&t0, &t4)
	z.Mul(z, &t4)
	z.Square(z)
	t3.Mul(&t3, z)
	t2.Mul(&t2, &t3)
	t2.Square(&t2)
	t2.Mul(&x, &t2)
	t4.Mul(&t4, &t2)
	t7.Mul(&t3, &t4)
	z.Mul(z, &t7)
	t8.Mul(&t0, z)
	t3.Square(&t2)
	t0.Mul(&t2, &t3)
	t7.Mul(&t7, &t3)
	t8.Mul(&t8, &t3)
	t7.Mul(&t0, &t7)
	t8.Square(&t8)
	t7.Mul(&t7, &t8)
	t8.Square(&t8)
	t7.Mul(&t7, &t8)
	t8.Square(&t8)
	t7.Mul(&t7, &t8)
	t8.Square(&t8)
	t7.Mul(&t7, &t8)
	t8.Square(&t8)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 13)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	t8.nSquare(&t8, 12)
	t7.Mul(&t7, &t8)
	z.Mul(z, &t7)
	z.Square(z)
	t7.Mul(&t7, z)
	t7.Square(&t7)
	t7.Mul(&x, &t7)
	z.Mul(z, &t7)
	t4.Mul(&t4, z)
	t4.Square(&t4)
	t4.Mul(&x, &t4)
	z.Mul(z, &t4)
	t7.Mul(&t7, z)
	t7.nSquare(&t7, 3)
	t6.Mul(&t6, &t7)
	z.Mul(z, &t6)
	t6.Mul(&t6, z)
	z.Mul(z, &t6)
	z.Square(z)
	z.Mul(&x, z)
	t6.Mul(&t6, z)
	t6.Square(&t6)
	t6.Mul(&x, &t6)
	t4.Mul(&t4, &t6)
	t6.Mul(&t6, &t4)
	t6.nSquare(&t6, 7)
	t5.Mul(&t5, &t6)
	t4.Mul(&t4, &t5)
	t5.Mul(&t5, &t4)
	t5.nSquare(&t5, 2)
	t1.Mul(&t1, &t5)
	t0.Mul(&t0, &t1)
	t3.Mul(&t3, &t0)
	t1.Mul(&t1, &t3)
	t1.Square(&t1)
	t1.Mul(&x, &t1)
	t3.Mul(&t3, &t1)
	t0.Mul(&t0, &t3)
	t2.Mul(&t2, &t0)
	t1.Mul(&t1, &t2)
	t2.Mul(&t2, &t1)
	t4.Mul(&t4, &t2)
	t4.nSquare(&t4, 127)
	t4.Mul(&t3, &t4)
	t4.nSquare(&t4, 131)
	t4.Mul(&t2, &t4)
	t4.nSquare(&t4, 127)
	t3.Mul(&t3, &t4)
	t3.nSquare(&t3, 131)
	t2.Mul(&t2, &t3)
	t2.nSquare(&t2, 128)
	t1.Mul(&t1, &t2)
	t1.nSquare(&t1, 128)
	t1.Mul(&t0, &t1)
	t1.nSquare(&t1, 128)
	t1.Mul(&t0, &t1)
	t1.nSquare(&t1, 128)
	t1.Mul(&t0, &t1)
	t1.nSquare(&t1, 128)
	t1.Mul(&t0, &t1)
	t1.nSquare(&t1, 128)
	t0.Mul(&t0, &t1)
	t0.nSquare(&t0, 113)
	z.Mul(z, &t0)

	return z
}
