// Code generated by internal/generator/cbrt. DO NOT EDIT.
package pp377

import (
	fp "github.com/yelhousni/fp2-cbrt/fp/pp377"
)

// lucasExponent is e = 3⁻¹ mod (p+1) as little-endian uint64 limbs.
var lucasExponent = [6]uint64{
	3195374304363544577,
	553507811686875136,
	13041240781673928704,
	12925598459776577839,
	17059168371523044115,
	40366104235498232,
}

// Cbrt sets z to the cube root of x and returns z.
// Uses the Okeya–Sakurai method (fastest).
// Returns nil if x is not a cubic residue.
func (z *E2) Cbrt(x *E2) *E2 {
	return z.cbrtOkeyaSakurai(x)
}

// cbrtTorus computes the cube root of x in E2 using the algebraic torus T₂(Fp).
func (z *E2) cbrtTorus(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		// Fp2 = Fp[u]/(u² - (-5)), so u³ = -5·u
		// x = x₁·u → y = a·u → y³ = a³·(-5)·u → a³ = x₁/(-5)
		var negA1OverBeta fp.Element
		betaInvNeg := fp.Element{
			330620507644336508,
			9878087358076053079,
			11461392860540703536,
			6973035786057818995,
			8846909097162646007,
			104838758629667239,
		}
		negA1OverBeta.Neg(&x.A1)
		negA1OverBeta.Mul(&negA1OverBeta, &betaInvNeg)
		if z.A1.Cbrt(&negA1OverBeta) == nil {
			return nil
		}
		z.A0.SetZero()
		return z.cbrtVerify(x)
	}

	// x₀², x₁²
	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	// N = x₀² + 5·x₁² (norm of x, since beta = -5)
	var norm, betaX1sq fp.Element
	betaX1sq.Set(&x1sq)
	fp.MulBy5(&betaX1sq)
	norm.Add(&x0sq, &betaX1sq)

	// m = cbrt(N) and normInv = 1/N
	m, normInv := cbrtAndNormInverse(&norm)

	// τ = 2·(x₀² - |β|·x₁²)/N = trace of x^{p-1} on T₂
	var tau fp.Element
	tau.Sub(&x0sq, &betaX1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	// σ = V_e(τ) where e = 3⁻¹ mod (p+1)
	sigma := lucasV(&tau)

	// Recovery: z₀ = x₀/(m·(σ-1)), z₁ = x₁/(m·(σ+1))
	var one, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	d0.Sub(&sigma, &one)
	d0.Mul(&m, &d0)
	d1.Add(&sigma, &one)
	d1.Mul(&m, &d1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	z.A0.Mul(&d1, &d0d1Inv).Mul(&z.A0, &x.A0)
	z.A1.Mul(&d0, &d0d1Inv).Mul(&z.A1, &x.A1)

	return z.cbrtVerify(x)
}

// cbrtOkeyaSakurai implements Okeya-Sakurai-style recovery with Hamburg's trick
// (Scott §2): a single exponentiation of w = U³·n yields cbrt(n), 1/n, and 1/U,
// eliminating the standalone Inverse(U) call.
func (z *E2) cbrtOkeyaSakurai(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1OverBeta fp.Element
		betaInvNeg := fp.Element{
			330620507644336508,
			9878087358076053079,
			11461392860540703536,
			6973035786057818995,
			8846909097162646007,
			104838758629667239,
		}
		negA1OverBeta.Neg(&x.A1)
		negA1OverBeta.Mul(&negA1OverBeta, &betaInvNeg)
		if z.A1.Cbrt(&negA1OverBeta) == nil {
			return nil
		}
		z.A0.SetZero()
		return z.cbrtVerify(x)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm, betaX1sq fp.Element
	betaX1sq.Set(&x1sq)
	fp.MulBy5(&betaX1sq)
	norm.Add(&x0sq, &betaX1sq)

	// U = -16·|β|·n·x0²·x1² = -80·n·x0²·x1² for β=-5
	var x0x1, U fp.Element
	x0x1.Mul(&x.A0, &x.A1)
	U.Square(&x0x1)
	U.Mul(&U, &norm)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	fp.MulBy5(&U)
	U.Neg(&U)

	// Hamburg trick: single exponentiation of w = U³·n
	var U2, U3, w fp.Element
	U2.Square(&U)
	U3.Mul(&U2, &U)
	w.Mul(&U3, &norm)

	var cbrtW, wInv fp.Element
	var tw fp.Element
	tw.ExpByCbrtHelperQMinus7Div9(w)
	cbrtW.Mul(&w, &tw)

	var cw2, cw4 fp.Element
	cw2.Square(&cbrtW)
	cw4.Square(&cw2)
	var cw5 fp.Element
	cw5.Mul(&cw4, &cbrtW)
	var tw2, tw4 fp.Element
	tw2.Square(&tw)
	tw4.Square(&tw2)
	wInv.Mul(&cw5, &tw4)

	// Recover 1/U, cbrt(n), 1/n
	var UInv, normInv, m fp.Element
	UInv.Mul(&U2, &norm)
	UInv.Mul(&UInv, &wInv)
	m.Mul(&cbrtW, &UInv)
	normInv.Mul(&U3, &wInv)

	// DeltaInv = n³·U⁻¹
	var n2, n3, deltaInv fp.Element
	n2.Square(&norm)
	n3.Mul(&n2, &norm)
	deltaInv.Mul(&n3, &UInv)

	// tau = 2·(x0² - |β|·x1²)/n
	var halfTau, tau fp.Element
	halfTau.Sub(&x0sq, &betaX1sq)
	halfTau.Mul(&halfTau, &normInv)
	tau.Double(&halfTau)

	Te, Te1 := lucasV2(&tau)

	var imY fp.Element
	imY.Double(&x0x1)
	imY.Mul(&imY, &normInv)

	var WA0, WA1 fp.Element
	WA0.Mul(&halfTau, &Te)
	WA0.Sub(&Te1, &WA0)
	WA1.Mul(&imY, &Te)

	var sIm, k fp.Element
	sIm.Double(&imY)
	k.Mul(&sIm, &deltaInv)

	var gamma E2
	gamma.A0.Mul(&WA1, &k)
	fp.MulBy5(&gamma.A0)
	gamma.A0.Neg(&gamma.A0)
	gamma.A1.Mul(&WA0, &k)

	var mInv fp.Element
	mInv.Square(&m)
	mInv.Mul(&mInv, &normInv)

	// z = x·conj(gamma)/m
	// For β=-5: (x0·g0 + 5·x1·g1, x1·g0 - x0·g1)
	var t1, t2 fp.Element
	t1.Mul(&x.A0, &gamma.A0)
	t2.Mul(&x.A1, &gamma.A1)
	fp.MulBy5(&t2)
	z.A0.Add(&t1, &t2)
	z.A0.Mul(&z.A0, &mInv)

	t1.Mul(&x.A1, &gamma.A0)
	t2.Mul(&x.A0, &gamma.A1)
	z.A1.Sub(&t1, &t2)
	z.A1.Mul(&z.A1, &mInv)

	return z.cbrtVerify(x)
}

// cbrtVerify checks z³ = x. Returns nil if not.
// For p mod 9 = 7 (and also p mod 9 = 4), the Fp cube root formula returns
// j = 0 deterministically (v₃(p-1) = 1), so only verification is needed.
func (z *E2) cbrtVerify(x *E2) *E2 {
	var c E2
	c.Square(z).Mul(&c, z)
	if !c.Equal(x) {
		return nil
	}
	return z
}

// cbrtAndNormInverse computes m = cbrt(norm) and normInv = 1/norm.
// For p mod 9 = 7: t = norm^((q-7)/9), m = norm · t, normInv = m⁵ · t⁴
func cbrtAndNormInverse(norm *fp.Element) (m, normInv fp.Element) {
	var t fp.Element
	t.ExpByCbrtHelperQMinus7Div9(*norm)

	// m = norm · t
	m.Mul(norm, &t)

	// normInv = m^5 · t^4
	var m2, m4 fp.Element
	m2.Square(&m)
	m4.Square(&m2)
	var mPow fp.Element
	mPow.Mul(&m4, &m) // m⁵

	var t2, t4 fp.Element
	t2.Square(&t)
	t4.Square(&t2)

	normInv.Mul(&mPow, &t4)

	return m, normInv
}

// lucasV2 returns both T_e = V_e(alpha) and T_{e+1} = V_{e+1}(alpha)
// where e is the lucasExponent. The final bit (bit 0 = 1) is handled
// explicitly to preserve both ladder outputs.
func lucasV2(alpha *fp.Element) (fp.Element, fp.Element) {
	var v0, v1, two fp.Element
	two.SetUint64(2)
	v0.Set(alpha)
	v1.Square(alpha).Sub(&v1, &two)

	var prod fp.Element
	for i := 374; i >= 1; i-- {
		bit := (lucasExponent[i/64] >> uint(i%64)) & 1
		prod.Mul(&v0, &v1).Sub(&prod, alpha)
		if bit == 0 {
			v1.Set(&prod)
			v0.Square(&v0).Sub(&v0, &two)
		} else {
			v0.Set(&prod)
			v1.Square(&v1).Sub(&v1, &two)
		}
	}
	// bit 0 = 1: T_e = v0*v1 - alpha, T_{e+1} = v1² - 2
	var Te, Te1 fp.Element
	Te.Mul(&v0, &v1).Sub(&Te, alpha)
	Te1.Square(&v1).Sub(&Te1, &two)
	return Te, Te1
}

func lucasV(alpha *fp.Element) fp.Element {
	Te, _ := lucasV2(alpha)
	return Te
}

// CbrtDirect computes the cube root using direct E2 exponentiation for benchmarking comparison.
// Uses e = 3⁻¹ mod ((p²-1)/3) as the exponent.
func (z *E2) cbrtDirect(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	z.expByE2Cbrt(*x)
	return z.cbrtVerify(x)
}

// CbrtFrobenius computes the E2 cube root using Frobenius decomposition
// and 2-bit windowed Strauss-Shamir multi-exponentiation.
func (z *E2) cbrtFrobenius(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	z.expByE2CbrtFrobenius(*x)
	return z.cbrtVerify(x)
}

func (z *E2) expByE2CbrtFrobenius(x E2) *E2 {
	var e0, e1 [6]uint64
	e0 = [6]uint64{17623453223078942038, 922513019478125226, 15586486611553363968, 3095920025918078116, 16134117903398705782, 67276840392497054}
	e1 = [6]uint64{14428078918715397461, 369005207791250090, 2545245829879435264, 8617065639851051893, 17521693605585213282, 26910736156998821}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [15]E2
	var xFrob2, xFrob3, x2, x3 E2
	x2.Square(&x)
	x3.Mul(&x2, &x)
	xFrob2.Square(&xFrob)
	xFrob3.Mul(&xFrob2, &xFrob)

	table[0].Set(&xFrob)
	table[1].Set(&xFrob2)
	table[2].Set(&xFrob3)
	table[3].Set(&x)
	table[4].Mul(&x, &xFrob)
	table[5].Mul(&x, &xFrob2)
	table[6].Mul(&x, &xFrob3)
	table[7].Set(&x2)
	table[8].Mul(&x2, &xFrob)
	table[9].Mul(&x2, &xFrob2)
	table[10].Mul(&x2, &xFrob3)
	table[11].Set(&x3)
	table[12].Mul(&x3, &xFrob)
	table[13].Mul(&x3, &xFrob2)
	table[14].Mul(&x3, &xFrob3)

	z.SetOne()

	for i := 374; i >= 0; i -= 2 {
		z.Square(z)
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)

		var w0, w1 uint64
		if bit < 63 {
			w0 = (e0[limb] >> bit) & 3
			w1 = (e1[limb] >> bit) & 3
		} else {
			w0 = (e0[limb] >> 63) & 1
			w1 = (e1[limb] >> 63) & 1
			if limb+1 < 6 {
				w0 |= (e0[limb+1] & 1) << 1
				w1 |= (e1[limb+1] & 1) << 1
			}
		}

		idx := w0<<2 | w1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}

func (z *E2) cbrtTorusPrac(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1OverBeta fp.Element
		betaInvNeg := fp.Element{
			330620507644336508,
			9878087358076053079,
			11461392860540703536,
			6973035786057818995,
			8846909097162646007,
			104838758629667239,
		}
		negA1OverBeta.Neg(&x.A1)
		negA1OverBeta.Mul(&negA1OverBeta, &betaInvNeg)
		if z.A1.Cbrt(&negA1OverBeta) == nil {
			return nil
		}
		z.A0.SetZero()
		return z.cbrtVerify(x)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm, betaX1sq fp.Element
	betaX1sq.Set(&x1sq)
	fp.MulBy5(&betaX1sq)
	norm.Add(&x0sq, &betaX1sq)

	m, normInv := cbrtAndNormInverse(&norm)

	var tau fp.Element
	tau.Sub(&x0sq, &betaX1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	sigma := lucasVPrac(&tau)

	var one, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	d0.Sub(&sigma, &one)
	d0.Mul(&m, &d0)
	d1.Add(&sigma, &one)
	d1.Mul(&m, &d1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	z.A0.Mul(&d1, &d0d1Inv).Mul(&z.A0, &x.A0)
	z.A1.Mul(&d0, &d0d1Inv).Mul(&z.A1, &x.A1)

	return z.cbrtVerify(x)
}

func (z *E2) cbrtFrobenius1bit(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	z.expByE2CbrtFrobenius1bit(*x)
	return z.cbrtVerify(x)
}

func (z *E2) expByE2CbrtFrobenius1bit(x E2) *E2 {
	var e0, e1 [6]uint64
	e0 = [6]uint64{17623453223078942038, 922513019478125226, 15586486611553363968, 3095920025918078116, 16134117903398705782, 67276840392497054}
	e1 = [6]uint64{14428078918715397461, 369005207791250090, 2545245829879435264, 8617065639851051893, 17521693605585213282, 26910736156998821}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [3]E2
	table[0].Set(&xFrob)     // (0,1)
	table[1].Set(&x)         // (1,0)
	table[2].Mul(&x, &xFrob) // (1,1)

	z.SetOne()

	for i := 376 - 1; i >= 0; i-- {
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)
		b0 := (e0[limb] >> bit) & 1
		b1 := (e1[limb] >> bit) & 1

		idx := b0<<1 | b1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}
