// Code generated by internal/generator/cbrt. DO NOT EDIT.
package ip575

// expByE2Cbrt is equivalent to z.Exp(x, 0x218b1c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71b7aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab).
// It uses an addition chain generated by github.com/mmcloughlin/addchain.
//
// Operations: 1129 squares 80 multiplies
func (z *E2) expByE2Cbrt(x E2) *E2 {
	var (
		t0 E2
		t1 E2
		t2 E2
		t3 E2
		t4 E2
		t5 E2
	)

	t0.Square(&x)
	z.Square(&t0)
	t1.Mul(&t0, z)
	t1.Square(&t1)
	t3.Mul(&t0, &t1)
	t1.Mul(&t0, &t3)
	t2.Mul(&x, &t1)
	z.Mul(z, &t2)
	t4.Square(z)
	z.Mul(&x, &t4)
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 5; s++ {
		t4.Square(&t4)
	}
	t2.Mul(&t2, &t4)
	t1.Mul(&t1, &t2)
	t2.Mul(&t2, &t1)
	t1.Mul(&t1, &t2)
	t1.Square(&t1)
	t1.Mul(&x, &t1)
	t2.Mul(&t2, &t1)
	t3.Mul(&t3, &t2)
	t1.Mul(&t1, &t3)
	t1.Square(&t1)
	t1.Mul(&x, &t1)
	t3.Mul(&t3, &t1)
	t2.Mul(&t2, &t3)
	t3.Mul(&t1, &t3)
	t2.Mul(&t2, &t3)
	t2.Square(&t2)
	t3.Mul(&t3, &t2)
	t1.Mul(&t1, &t3)
	t1.Square(&t1)
	t1.Mul(&x, &t1)
	t2.Mul(&t2, &t1)
	t3.Mul(&t3, &t2)
	t2.Mul(&t2, &t3)
	
	for s := 0; s < 2; s++ {
		t2.Square(&t2)
	}
	t0.Mul(&t0, &t2)
	t1.Mul(&t1, &t0)
	t0.Mul(&t0, &t1)
	t2.Square(&t0)
	t5.Mul(&x, &t2)
	t1.Mul(&t1, &t5)
	t2.Mul(&t3, &t1)
	t1.Mul(&t5, &t1)
	t2.Mul(&t2, &t1)
	t0.Mul(&t0, &t2)
	t2.Mul(&t2, &t0)
	t4.Mul(&t0, &t2)
	t5.Mul(&t5, &t4)
	t2.Mul(&t2, &t5)
	t0.Mul(&t0, &t2)
	t1.Mul(&t1, &t0)
	t5.Mul(&t4, &t1)
	t1.Mul(&t1, &t5)
	t3.Mul(&t3, &t1)
	t4.Mul(&t4, &t1)
	
	for s := 0; s < 34; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t4.Square(&t4)
	}
	t4.Mul(&t2, &t4)
	
	for s := 0; s < 35; s++ {
		t4.Square(&t4)
	}
	t3.Mul(&t3, &t4)
	
	for s := 0; s < 31; s++ {
		t3.Square(&t3)
	}
	t2.Mul(&t2, &t3)
	
	for s := 0; s < 35; s++ {
		t2.Square(&t2)
	}
	t1.Mul(&t1, &t2)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t1.Mul(&t0, &t1)
	
	for s := 0; s < 32; s++ {
		t1.Square(&t1)
	}
	t0.Mul(&t0, &t1)
	
	for s := 0; s < 7; s++ {
		t0.Square(&t0)
	}
	z.Mul(z, &t0)
	
	return z
}
