// Code generated by internal/generator/cbrt. DO NOT EDIT.
package pp254

import (
	fp "github.com/yelhousni/fp2-cbrt/fp/pp254"
)

// lucasExponent is e = 3⁻¹ mod (p+1) as little-endian uint64 limbs.
var lucasExponent = [4]uint64{
	7593120314996402627,
	15936870763965662084,
	16724893366231265993,
	1162332755600990221,
}

func (z *E2) Cbrt(x *E2) *E2 {
	return z.cbrtTorus(x)
}

func (z *E2) cbrtTorus(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm fp.Element
	norm.Add(&x0sq, &x1sq)

	m, normInv, ok := cbrtAndNormInverse(&norm)
	if !ok {
		return nil
	}

	var tau fp.Element
	tau.Sub(&x0sq, &x1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	sigma := lucasV(&tau)

	var one, sigmaM1, sigmaP1, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	sigmaM1.Sub(&sigma, &one)
	sigmaP1.Add(&sigma, &one)
	d0.Mul(&m, &sigmaM1)
	d1.Mul(&m, &sigmaP1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	var y E2
	y.A0.Mul(&d1, &d0d1Inv).Mul(&y.A0, &x.A0)
	y.A1.Mul(&d0, &d0d1Inv).Mul(&y.A1, &x.A1)

	return z.cbrtVerifyAndAdjust(x, &y)
}

// cbrtOkeyaSakurai implements Okeya-Sakurai-style recovery with Hamburg's trick
// (Scott §2): a single exponentiation of w = U³·n yields cbrt(n), 1/n, and 1/U,
// eliminating the standalone Inverse(U) call.
func (z *E2) cbrtOkeyaSakurai(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq, norm fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	norm.Add(&x0sq, &x1sq)

	// U = -16·n·x0²·x1²
	var x0x1, U fp.Element
	x0x1.Mul(&x.A0, &x.A1)
	U.Square(&x0x1)
	U.Mul(&U, &norm)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	U.Neg(&U)

	// Hamburg trick: single exponentiation of w = U³·n
	var U2, U3, w fp.Element
	U2.Square(&U)
	U3.Mul(&U2, &U)
	w.Mul(&U3, &norm)

	var cbrtW, wInv fp.Element
	var tw fp.Element
	tw.ExpByCbrtHelperQMinus19Div27(w)
	cbrtW.Mul(&w, &tw)

	var cw2 fp.Element
	cw2.Square(&cbrtW)
	var tw2, tw4, tw8 fp.Element
	tw2.Square(&tw)
	tw4.Square(&tw2)
	tw8.Square(&tw4)
	wInv.Mul(&tw8, &tw2) // tw^10
	var cw4, cw8, cw16, cw17 fp.Element
	cw4.Square(&cw2)
	cw8.Square(&cw4)
	cw16.Square(&cw8)
	cw17.Mul(&cw16, &cbrtW)
	wInv.Mul(&wInv, &cw17)

	// Recover 1/U, cbrt(n), 1/n
	var UInv, normInv fp.Element
	UInv.Mul(&U2, &norm)
	UInv.Mul(&UInv, &wInv)
	var m fp.Element
	m.Mul(&cbrtW, &UInv)
	normInv.Mul(&U3, &wInv)

	// Verify m³ = norm, adjust by ζ if needed
	var m2 fp.Element
	m2.Square(&m)
	var c fp.Element
	c.Mul(&m2, &m)
	if !c.Equal(&norm) {
		var zeta = fp.Element{
			9092840637269024442,
			11284133545212953584,
			7919372827184455520,
			1596114425137527684,
		}
		var zeta2 = fp.Element{
			1735008219140503419,
			10465829585049341007,
			6017168831245289042,
			1570250484855163800,
		}
		var omega = fp.Element{
			8183898218631979349,
			12014359695528440611,
			12263358156045030468,
			3187210487005268291,
		}
		var omega2 = fp.Element{
			3697675806616062876,
			9065277094688085689,
			6918009208039626314,
			2775033306905974752,
		}

		var cw2 fp.Element
		cw2.Mul(&c, &omega2)
		if cw2.Equal(&norm) {
			m.Mul(&m, &zeta)
		} else {
			var cw fp.Element
			cw.Mul(&c, &omega)
			if cw.Equal(&norm) {
				m.Mul(&m, &zeta2)
			} else {
				return nil
			}
		}
	}

	// DeltaInv = n³·U⁻¹
	var n2, n3, deltaInv fp.Element
	n2.Square(&norm)
	n3.Mul(&n2, &norm)
	deltaInv.Mul(&n3, &UInv)

	var halfTau, tau fp.Element
	halfTau.Sub(&x0sq, &x1sq)
	halfTau.Mul(&halfTau, &normInv)
	tau.Double(&halfTau)

	Te, Te1 := lucasV2(&tau)

	var imY fp.Element
	imY.Double(&x0x1)
	imY.Mul(&imY, &normInv)

	var WA0, WA1 fp.Element
	WA0.Mul(&halfTau, &Te)
	WA0.Sub(&Te1, &WA0)
	WA1.Mul(&imY, &Te)

	var sIm, k fp.Element
	sIm.Double(&imY)
	k.Mul(&sIm, &deltaInv)

	var gamma E2
	gamma.A0.Mul(&WA1, &k)
	gamma.A0.Neg(&gamma.A0)
	gamma.A1.Mul(&WA0, &k)

	var mInv fp.Element
	mInv.Square(&m)
	mInv.Mul(&mInv, &normInv)

	var y E2
	var t1, t2 fp.Element
	t1.Mul(&x.A0, &gamma.A0)
	t2.Mul(&x.A1, &gamma.A1)
	y.A0.Add(&t1, &t2)
	y.A0.Mul(&y.A0, &mInv)

	t1.Mul(&x.A1, &gamma.A0)
	t2.Mul(&x.A0, &gamma.A1)
	y.A1.Sub(&t1, &t2)
	y.A1.Mul(&y.A1, &mInv)

	return z.cbrtVerifyAndAdjust(x, &y)
}

// cbrtVerifyAndAdjust verifies y³ = x, adjusting by 9th roots of unity if needed.
// For p mod 9 = 1: there are primitive 9th roots of unity in Fp.
func (z *E2) cbrtVerifyAndAdjust(x *E2, y *E2) *E2 {
	var c E2
	c.Square(y).Mul(&c, y)
	if c.Equal(x) {
		return z.Set(y)
	}

	var omega = fp.Element{
		8183898218631979349,
		12014359695528440611,
		12263358156045030468,
		3187210487005268291,
	}
	var omega2 = fp.Element{
		3697675806616062876,
		9065277094688085689,
		6918009208039626314,
		2775033306905974752,
	}
	var zeta = fp.Element{
		9092840637269024442,
		11284133545212953584,
		7919372827184455520,
		1596114425137527684,
	}
	var zeta2 = fp.Element{
		1735008219140503419,
		10465829585049341007,
		6017168831245289042,
		1570250484855163800,
	}

	var cw2 E2
	cw2.A0.Mul(&c.A0, &omega2)
	cw2.A1.Mul(&c.A1, &omega2)
	if cw2.Equal(x) {
		z.A0.Mul(&y.A0, &zeta)
		z.A1.Mul(&y.A1, &zeta)
		return z
	}

	var cw E2
	cw.A0.Mul(&c.A0, &omega)
	cw.A1.Mul(&c.A1, &omega)
	if cw.Equal(x) {
		z.A0.Mul(&y.A0, &zeta2)
		z.A1.Mul(&y.A1, &zeta2)
		return z
	}

	return nil
}

// cbrtAndNormInverse computes m = cbrt(norm) and normInv = 1/norm.
func cbrtAndNormInverse(norm *fp.Element) (m, normInv fp.Element, ok bool) {
	var t fp.Element
	t.ExpByCbrtHelperQMinus19Div27(*norm)
	m.Mul(norm, &t)

	// normInv = m^17 · t^10
	var m2 fp.Element
	m2.Square(&m)
	var t2, t4, t8 fp.Element
	t2.Square(&t)
	t4.Square(&t2)
	t8.Square(&t4)
	normInv.Mul(&t8, &t2) // t^10

	var m4, m8, m16 fp.Element
	m4.Square(&m2)
	m8.Square(&m4)
	m16.Square(&m8)
	t2.Mul(&m16, &m) // m^17 (reuse t2)
	normInv.Mul(&normInv, &t2)

	// Verify m³ = norm, adjust by ζ if needed
	var c fp.Element
	c.Mul(&m2, &m)
	if !c.Equal(norm) {
		var zeta = fp.Element{
			9092840637269024442,
			11284133545212953584,
			7919372827184455520,
			1596114425137527684,
		}
		var zeta2 = fp.Element{
			1735008219140503419,
			10465829585049341007,
			6017168831245289042,
			1570250484855163800,
		}
		var omega = fp.Element{
			8183898218631979349,
			12014359695528440611,
			12263358156045030468,
			3187210487005268291,
		}
		var omega2 = fp.Element{
			3697675806616062876,
			9065277094688085689,
			6918009208039626314,
			2775033306905974752,
		}

		var cw2 fp.Element
		cw2.Mul(&c, &omega2)
		if cw2.Equal(norm) {
			m.Mul(&m, &zeta)
		} else {
			var cw fp.Element
			cw.Mul(&c, &omega)
			if cw.Equal(norm) {
				m.Mul(&m, &zeta2)
			} else {
				return m, normInv, false
			}
		}
	}

	return m, normInv, true
}

// lucasV2 returns both T_e = V_e(alpha) and T_{e+1} = V_{e+1}(alpha)
// where e is the lucasExponent. The final bit (bit 0 = 1) is handled
// explicitly to preserve both ladder outputs.
func lucasV2(alpha *fp.Element) (fp.Element, fp.Element) {
	var v0, v1, two fp.Element
	two.SetUint64(2)
	v0.Set(alpha)
	v1.Square(alpha).Sub(&v1, &two)

	var prod fp.Element
	for i := 251; i >= 1; i-- {
		bit := (lucasExponent[i/64] >> uint(i%64)) & 1
		prod.Mul(&v0, &v1).Sub(&prod, alpha)
		if bit == 0 {
			v1.Set(&prod)
			v0.Square(&v0).Sub(&v0, &two)
		} else {
			v0.Set(&prod)
			v1.Square(&v1).Sub(&v1, &two)
		}
	}
	// bit 0 = 1: T_e = v0*v1 - alpha, T_{e+1} = v1² - 2
	var Te, Te1 fp.Element
	Te.Mul(&v0, &v1).Sub(&Te, alpha)
	Te1.Square(&v1).Sub(&Te1, &two)
	return Te, Te1
}

func lucasV(alpha *fp.Element) fp.Element {
	Te, _ := lucasV2(alpha)
	return Te
}

func (z *E2) cbrtDirect(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2Cbrt(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

// CbrtFrobenius computes the E2 cube root using Frobenius decomposition
// and 2-bit windowed Strauss-Shamir multi-exponentiation.
func (z *E2) cbrtFrobenius(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2CbrtFrobenius(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) expByE2CbrtFrobenius(x E2) *E2 {
	var e0, e1 [4]uint64
	e0 = [4]uint64{11330118615407775612, 13329482909165958675, 6094068723619673846, 1420628923512321382}
	e1 = [4]uint64{3736998300411372985, 15839356218909848207, 7815919431097959468, 258296167911331160}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [15]E2
	var xFrob2, xFrob3, x2, x3 E2
	x2.Square(&x)
	x3.Mul(&x2, &x)
	xFrob2.Square(&xFrob)
	xFrob3.Mul(&xFrob2, &xFrob)

	table[0].Set(&xFrob)
	table[1].Set(&xFrob2)
	table[2].Set(&xFrob3)
	table[3].Set(&x)
	table[4].Mul(&x, &xFrob)
	table[5].Mul(&x, &xFrob2)
	table[6].Mul(&x, &xFrob3)
	table[7].Set(&x2)
	table[8].Mul(&x2, &xFrob)
	table[9].Mul(&x2, &xFrob2)
	table[10].Mul(&x2, &xFrob3)
	table[11].Set(&x3)
	table[12].Mul(&x3, &xFrob)
	table[13].Mul(&x3, &xFrob2)
	table[14].Mul(&x3, &xFrob3)

	z.SetOne()

	// 253 bits is odd: process top bit to align
	{
		b0 := (e0[3] >> 60) & 1
		b1 := (e1[3] >> 60) & 1
		idx := b0<<2 | b1
		if idx != 0 {
			z.Set(&table[idx-1])
		}
	}

	for i := 250; i >= 0; i -= 2 {
		z.Square(z)
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)

		var w0, w1 uint64
		if bit < 63 {
			w0 = (e0[limb] >> bit) & 3
			w1 = (e1[limb] >> bit) & 3
		} else {
			w0 = (e0[limb] >> 63) & 1
			w1 = (e1[limb] >> 63) & 1
			if limb+1 < 4 {
				w0 |= (e0[limb+1] & 1) << 1
				w1 |= (e1[limb+1] & 1) << 1
			}
		}

		idx := w0<<2 | w1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}

func (z *E2) cbrtTorusPrac(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm fp.Element
	norm.Add(&x0sq, &x1sq)

	m, normInv, ok := cbrtAndNormInverse(&norm)
	if !ok {
		return nil
	}

	var tau fp.Element
	tau.Sub(&x0sq, &x1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	sigma := lucasVPrac(&tau)

	var one, sigmaM1, sigmaP1, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	sigmaM1.Sub(&sigma, &one)
	sigmaP1.Add(&sigma, &one)
	d0.Mul(&m, &sigmaM1)
	d1.Mul(&m, &sigmaP1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	var y E2
	y.A0.Mul(&d1, &d0d1Inv).Mul(&y.A0, &x.A0)
	y.A1.Mul(&d0, &d0d1Inv).Mul(&y.A1, &x.A1)

	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) cbrtFrobenius1bit(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2CbrtFrobenius1bit(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) expByE2CbrtFrobenius1bit(x E2) *E2 {
	var e0, e1 [4]uint64
	e0 = [4]uint64{11330118615407775612, 13329482909165958675, 6094068723619673846, 1420628923512321382}
	e1 = [4]uint64{3736998300411372985, 15839356218909848207, 7815919431097959468, 258296167911331160}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [3]E2
	table[0].Set(&xFrob)     // (0,1)
	table[1].Set(&x)         // (1,0)
	table[2].Mul(&x, &xFrob) // (1,1)

	z.SetOne()

	for i := 253 - 1; i >= 0; i-- {
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)
		b0 := (e0[limb] >> bit) & 1
		b1 := (e1[limb] >> bit) & 1

		idx := b0<<1 | b1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}
