package pp254

import fp "github.com/yelhousni/fp2-cbrt/fp/pp254"

// lucasVPracFactoredUnrolled computes V_e(α) using e = (6u²+1)(2u²+2u+1)
// with two unrolled PRAC chains composed via V_{f1·f2}(α) = V_{f2}(V_{f1}(α)).
// Cost: 222 + 214 = 436 field ops.
func lucasVPracFactoredUnrolled(alpha *fp.Element) fp.Element {
	var A, B, C fp.Element
	var T, T2, T3 fp.Element
	var two fp.Element
	two.SetUint64(2)

	// Phase 1: V_{f1}(alpha), f1 = 6u²+1, 222 ops
	A.Set(alpha)
	B.Set(alpha)
	C.Set(&two)

	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	C.Mul(&A, &C).Sub(&C, &B)
	A.Set(&T3)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	C.Mul(&A, &C).Sub(&C, &B)
	A.Set(&T3)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)

	// Phase 2: V_{f2}(V_{f1}(alpha)), f2 = 2u²+2u+1, 214 ops
	alpha2 := A
	A.Set(&alpha2)
	B.Set(&alpha2)
	C.Set(&two)

	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	C.Mul(&A, &C).Sub(&C, &B)
	A.Set(&T3)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)

	return A
}

// lucasVPracUnrolled computes V_e(α) using a single unrolled PRAC chain.
// Cost: 441 field ops.
func lucasVPracUnrolled(alpha *fp.Element) fp.Element {
	var A, B, C fp.Element
	var T, T2, T3 fp.Element
	var two fp.Element
	two.SetUint64(2)

	A.Set(alpha)
	B.Set(alpha)
	C.Set(&two)

	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	A, B = B, A
	T.Mul(&C, &B).Sub(&T, &A)
	B.Square(&B).Sub(&B, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	T2.Mul(&T, &A).Sub(&T2, &B)
	A.Set(&T3)
	B.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Square(&A).Sub(&T2, &two)
	T3.Mul(&T2, &A).Sub(&T3, &A)
	A.Set(&T3)
	T3.Mul(&T2, &T).Sub(&T3, &C)
	C.Set(&B)
	B.Set(&T3)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	A.Square(&A).Sub(&A, &two)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	T2.Mul(&T, &A).Sub(&T2, &B)
	B.Mul(&T, &B).Sub(&B, &A)
	A.Set(&T2)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A, B = B, A
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &C).Sub(&T, &B)
	A.Square(&A).Sub(&A, &two)
	C.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	T.Mul(&A, &B).Sub(&T, &C)
	C.Set(&B)
	B.Set(&T)
	A.Mul(&A, &B).Sub(&A, &C)
	B.Set(&A)
	C.Set(&two)

	return A
}
