// Code generated by internal/generator/cbrt. DO NOT EDIT.
package ip381

import (
	fp "github.com/yelhousni/fp2-cbrt/fp/ip381"
)

// lucasExponent is e = 3⁻¹ mod (p+1) as little-endian uint64 limbs.
var lucasExponent = [6]uint64{
	12297829382473034411,
	12297829382473034410,
	12297829382473034410,
	12297829382473034410,
	12297829382473034410,
	656024345720302250,
}

func (z *E2) Cbrt(x *E2) *E2 {
	return z.cbrtTorus(x)
}

func (z *E2) cbrtTorus(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm fp.Element
	norm.Add(&x0sq, &x1sq)

	m, normInv, ok := cbrtAndNormInverse(&norm)
	if !ok {
		return nil
	}

	var tau fp.Element
	tau.Sub(&x0sq, &x1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	sigma := lucasV(&tau)

	var one, sigmaM1, sigmaP1, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	sigmaM1.Sub(&sigma, &one)
	sigmaP1.Add(&sigma, &one)
	d0.Mul(&m, &sigmaM1)
	d1.Mul(&m, &sigmaP1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	var y E2
	y.A0.Mul(&d1, &d0d1Inv).Mul(&y.A0, &x.A0)
	y.A1.Mul(&d0, &d0d1Inv).Mul(&y.A1, &x.A1)

	return z.cbrtVerifyAndAdjust(x, &y)
}

// cbrtOkeyaSakurai implements Ben Smith's Okeya-Sakurai-style recovery.
//
// Given x = (x0, x1) with norm n = x0²+x1², trace t = 2x0, and
// y = x/conj(x) (torus element), it computes y^e via:
//
//	W := T_{e+1} - y⁻¹·T_e  =  s·y^e
//	y^e = W · s / Delta       (since 1/s = s/Delta with Delta = s²)
//
// The key insight: Delta = (t/n)²·(t²-4n) and U = n·t²·(t²-4n) are
// known before the ladder, so Inverse(U) is a PRE-ladder inversion
// (unlike cbrtTorus where the inversion is post-ladder).
func (z *E2) cbrtOkeyaSakurai(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq, norm fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	norm.Add(&x0sq, &x1sq)

	// U = n·t²·(t²-4n) = n·4x0²·(-4x1²) = -16·n·x0²·x1²
	// All quantities known before exponentiation and ladder.
	var x0x1, U fp.Element
	x0x1.Mul(&x.A0, &x.A1)
	U.Square(&x0x1)
	U.Mul(&U, &norm)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	U.Double(&U)
	U.Neg(&U) // U = -16·n·x0²·x1²

	// Pre-ladder inversion (not blocked on any ladder output)
	var UInv fp.Element
	UInv.Inverse(&U)

	// Exponentiation of norm → m = cbrt(norm), normInv
	m, normInv, ok := cbrtAndNormInverse(&norm)
	if !ok {
		return nil
	}

	// DeltaInv = n³·U⁻¹
	// (since Delta = t²(t²-4n)/n² and U = n·t²·(t²-4n), so 1/Delta = n³·U⁻¹)
	var n2, n3, deltaInv fp.Element
	n2.Square(&norm)
	n3.Mul(&n2, &norm)
	deltaInv.Mul(&n3, &UInv)

	// tau = T_1 = y + y⁻¹ = 2(x0²-x1²)/n
	// halfTau = tau/2 = (x0²-x1²)/n = Re(y)
	var halfTau, tau fp.Element
	halfTau.Sub(&x0sq, &x1sq)
	halfTau.Mul(&halfTau, &normInv)
	tau.Double(&halfTau)

	// Ladder → T_e, T_{e+1}
	Te, Te1 := lucasV2(&tau)

	// Im(y) = 2·x0·x1/n
	var imY fp.Element
	imY.Double(&x0x1)
	imY.Mul(&imY, &normInv)

	// W = T_{e+1} - y⁻¹·T_e  where y⁻¹ = (Re(y), -Im(y))
	// W.A0 = T_{e+1} - Re(y)·T_e
	// W.A1 = Im(y)·T_e
	var WA0, WA1 fp.Element
	WA0.Mul(&halfTau, &Te)
	WA0.Sub(&Te1, &WA0)
	WA1.Mul(&imY, &Te)

	// gamma = y^e = W·s·DeltaInv
	// s = (0, 2·Im(y)) as Fp2, so s_im = 2·Im(y) = 4·x0·x1/n
	// W·s = (W.A0 + W.A1·u)·(s_im·u) = (-W.A1·s_im, W.A0·s_im)
	// gamma = (-W.A1·s_im·DeltaInv, W.A0·s_im·DeltaInv)
	var sIm, k fp.Element
	sIm.Double(&imY)
	k.Mul(&sIm, &deltaInv)

	var gamma E2
	gamma.A0.Mul(&WA1, &k)
	gamma.A0.Neg(&gamma.A0)
	gamma.A1.Mul(&WA0, &k)

	// Recover z = cbrt(x) from gamma = y^e (torus representation)
	// gamma = z/conj(z), N(z) = m, so z² = m·gamma
	// z = x·conj(gamma)/m  (since x = z³, gamma has norm 1)
	// mInv = m²·normInv  (since m³ = n)
	var mInv fp.Element
	mInv.Square(&m)
	mInv.Mul(&mInv, &normInv)

	// x·conj(gamma) = (x0·g0 + x1·g1, x1·g0 - x0·g1)
	var y E2
	var t1, t2 fp.Element
	t1.Mul(&x.A0, &gamma.A0)
	t2.Mul(&x.A1, &gamma.A1)
	y.A0.Add(&t1, &t2)
	y.A0.Mul(&y.A0, &mInv)

	t1.Mul(&x.A1, &gamma.A0)
	t2.Mul(&x.A0, &gamma.A1)
	y.A1.Sub(&t1, &t2)
	y.A1.Mul(&y.A1, &mInv)

	return z.cbrtVerifyAndAdjust(x, &y)
}

// cbrtVerifyAndAdjust for p mod 9 = 4:
// 3 | (p-1) so cube roots of unity exist, but 9 ∤ (p-1) so no 9th roots.
func (z *E2) cbrtVerifyAndAdjust(x *E2, y *E2) *E2 {
	var c E2
	c.Square(y).Mul(&c, y)
	if c.Equal(x) {
		return z.Set(y)
	}

	// Primitive cube roots of unity ω, ω² in Fp (Montgomery form)
	var omega = fp.Element{
		16450804138475314484,
		11985234970664749306,
		4315746388836120995,
		5287851689109039980,
		8076073126744894038,
		125415377056785313,
	}
	var omega2 = fp.Element{
		1995939935234237122,
		6461509103044802309,
		14130997684873430620,
		13158892384600511635,
		10370670946964657577,
		1108570920842730590,
	}

	// For non-unique cube root: check y³·ω² = x, then z = y·ω
	// (since ω³ = 1, (y·ω)³ = y³·ω³ = y³, need y³·ω^(-1) = x, i.e. y³ = x·ω)
	// Actually: if y³ = x·ω then (y·ω)³ = y³·ω³ = x·ω·1 ≠ x
	// Correct: if c = y³ ≠ x, check c·ω² = x (then y·ω is a cube root since
	// (y·ω)³ = y³·ω³ = y³ = c, and c·ω² = x means c = x·ω, so
	// we need to find z s.t. z³=x. Since c=y³=x·ω, we need z=y·ζ where ζ³=ω⁻¹=ω²
	// But ζ = ω^(2/3) which doesn't make sense. Let me reconsider.
	//
	// Actually for p mod 9 = 4, there are no 9th roots of unity (only cube roots).
	// The verify-and-adjust is simpler:
	// If y³ = x, done.
	// If y³ = x·ω, then (y·ω)³ = y³·ω³ = y³ = x·ω ≠ x. Wrong.
	// If c·ω = x (i.e. y³·ω = x), then (y/ω^(1/3))³ = x.
	// But ω^(1/3) exists only if 9 | (p-1), which is not the case here.
	//
	// So for p mod 9 = 4: if y³ ≠ x, the element is NOT a cubic residue.
	// Wait — let me reconsider. The cbrt helper exponent should give the correct
	// cube root when one exists. The issue is the Fp cbrt:
	// For p mod 9 = 4: (2p+1)/9 is the cbrt exponent, and cbrt is UNIQUE.
	// So no adjustment should be needed for the Fp cbrt step.
	//
	// But the torus approach could still have sign issues. Let me just check all three:

	var cw2 E2
	cw2.A0.Mul(&c.A0, &omega2)
	cw2.A1.Mul(&c.A1, &omega2)
	if cw2.Equal(x) {
		// This shouldn't happen for p mod 9 = 4 if the Fp cbrt is unique
		// But handle it defensively
		z.A0.Mul(&y.A0, &omega)
		z.A1.Mul(&y.A1, &omega)
		var check E2
		check.Square(z).Mul(&check, z)
		if check.Equal(x) {
			return z
		}
	}

	var cw E2
	cw.A0.Mul(&c.A0, &omega)
	cw.A1.Mul(&c.A1, &omega)
	if cw.Equal(x) {
		z.A0.Mul(&y.A0, &omega2)
		z.A1.Mul(&y.A1, &omega2)
		var check E2
		check.Square(z).Mul(&check, z)
		if check.Equal(x) {
			return z
		}
	}

	return nil
}

// cbrtAndNormInverse computes m = cbrt(norm) and normInv = 1/norm.
func cbrtAndNormInverse(norm *fp.Element) (m, normInv fp.Element, ok bool) {
	var t fp.Element
	t.ExpByCbrtHelperQMinus4Div9(*norm)
	var t2 fp.Element
	t2.Square(&t)
	m.Mul(norm, &t2) // m = norm · t²

	// normInv = m² · t⁵
	var m2 fp.Element
	m2.Square(&m)

	var t4 fp.Element
	t4.Square(&t2)
	normInv.Mul(&t4, &t) // t⁵
	normInv.Mul(&normInv, &m2)

	// For p mod 9 = 4: Fp cbrt is unique (2p+1 ≡ 0 mod 9)
	// Verify m³ = norm
	var c fp.Element
	c.Mul(&m2, &m)
	if !c.Equal(norm) {
		return m, normInv, false
	}

	return m, normInv, true
}

// lucasV2 returns both T_e = V_e(alpha) and T_{e+1} = V_{e+1}(alpha)
// where e is the lucasExponent. The final bit (bit 0 = 1) is handled
// explicitly to preserve both ladder outputs.
func lucasV2(alpha *fp.Element) (fp.Element, fp.Element) {
	var v0, v1, two fp.Element
	two.SetUint64(2)
	v0.Set(alpha)
	v1.Square(alpha).Sub(&v1, &two)

	var prod fp.Element
	for i := 378; i >= 1; i-- {
		bit := (lucasExponent[i/64] >> uint(i%64)) & 1
		prod.Mul(&v0, &v1).Sub(&prod, alpha)
		if bit == 0 {
			v1.Set(&prod)
			v0.Square(&v0).Sub(&v0, &two)
		} else {
			v0.Set(&prod)
			v1.Square(&v1).Sub(&v1, &two)
		}
	}
	// bit 0 = 1: T_e = v0*v1 - alpha, T_{e+1} = v1² - 2
	var Te, Te1 fp.Element
	Te.Mul(&v0, &v1).Sub(&Te, alpha)
	Te1.Square(&v1).Sub(&Te1, &two)
	return Te, Te1
}

func lucasV(alpha *fp.Element) fp.Element {
	Te, _ := lucasV2(alpha)
	return Te
}

func (z *E2) cbrtDirect(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2Cbrt(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

// CbrtFrobenius computes the E2 cube root using Frobenius decomposition
// and 2-bit windowed Strauss-Shamir multi-exponentiation.
func (z *E2) cbrtFrobenius(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2CbrtFrobenius(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) expByE2CbrtFrobenius(x E2) *E2 {
	var e0, e1 [6]uint64
	e0 = [6]uint64{16397105843297379214, 10248191152060862008, 4099276460824344803, 16397105843297379214, 10248191152060862008, 874699127627069667}
	e1 = [6]uint64{4099276460824344803, 16397105843297379214, 10248191152060862008, 4099276460824344803, 16397105843297379214, 218674781906767416}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [15]E2
	var xFrob2, xFrob3, x2, x3 E2
	x2.Square(&x)
	x3.Mul(&x2, &x)
	xFrob2.Square(&xFrob)
	xFrob3.Mul(&xFrob2, &xFrob)

	table[0].Set(&xFrob)
	table[1].Set(&xFrob2)
	table[2].Set(&xFrob3)
	table[3].Set(&x)
	table[4].Mul(&x, &xFrob)
	table[5].Mul(&x, &xFrob2)
	table[6].Mul(&x, &xFrob3)
	table[7].Set(&x2)
	table[8].Mul(&x2, &xFrob)
	table[9].Mul(&x2, &xFrob2)
	table[10].Mul(&x2, &xFrob3)
	table[11].Set(&x3)
	table[12].Mul(&x3, &xFrob)
	table[13].Mul(&x3, &xFrob2)
	table[14].Mul(&x3, &xFrob3)

	z.SetOne()

	for i := 378; i >= 0; i -= 2 {
		z.Square(z)
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)

		var w0, w1 uint64
		if bit < 63 {
			w0 = (e0[limb] >> bit) & 3
			w1 = (e1[limb] >> bit) & 3
		} else {
			w0 = (e0[limb] >> 63) & 1
			w1 = (e1[limb] >> 63) & 1
			if limb+1 < 6 {
				w0 |= (e0[limb+1] & 1) << 1
				w1 |= (e1[limb+1] & 1) << 1
			}
		}

		idx := w0<<2 | w1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}

func (z *E2) cbrtTorusPrac(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}

	if x.A0.IsZero() {
		var negA1 fp.Element
		negA1.Neg(&x.A1)
		var y E2
		if y.A1.Cbrt(&negA1) == nil {
			return nil
		}
		y.A0.SetZero()
		return z.cbrtVerifyAndAdjust(x, &y)
	}

	var x0sq, x1sq fp.Element
	x0sq.Square(&x.A0)
	x1sq.Square(&x.A1)
	var norm fp.Element
	norm.Add(&x0sq, &x1sq)

	m, normInv, ok := cbrtAndNormInverse(&norm)
	if !ok {
		return nil
	}

	var tau fp.Element
	tau.Sub(&x0sq, &x1sq)
	tau.Double(&tau)
	tau.Mul(&tau, &normInv)

	sigma := lucasVPrac(&tau)

	var one, sigmaM1, sigmaP1, d0, d1, d0d1, d0d1Inv fp.Element
	one.SetOne()
	sigmaM1.Sub(&sigma, &one)
	sigmaP1.Add(&sigma, &one)
	d0.Mul(&m, &sigmaM1)
	d1.Mul(&m, &sigmaP1)

	d0d1.Mul(&d0, &d1)
	d0d1Inv.Inverse(&d0d1)

	var y E2
	y.A0.Mul(&d1, &d0d1Inv).Mul(&y.A0, &x.A0)
	y.A1.Mul(&d0, &d0d1Inv).Mul(&y.A1, &x.A1)

	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) cbrtFrobenius1bit(x *E2) *E2 {
	if x.A1.IsZero() {
		if z.A0.Cbrt(&x.A0) == nil {
			return nil
		}
		z.A1.SetZero()
		return z
	}
	var y E2
	y.expByE2CbrtFrobenius1bit(*x)
	return z.cbrtVerifyAndAdjust(x, &y)
}

func (z *E2) expByE2CbrtFrobenius1bit(x E2) *E2 {
	var e0, e1 [6]uint64
	e0 = [6]uint64{16397105843297379214, 10248191152060862008, 4099276460824344803, 16397105843297379214, 10248191152060862008, 874699127627069667}
	e1 = [6]uint64{4099276460824344803, 16397105843297379214, 10248191152060862008, 4099276460824344803, 16397105843297379214, 218674781906767416}

	var xFrob E2
	xFrob.Conjugate(&x)

	var table [3]E2
	table[0].Set(&xFrob)     // (0,1)
	table[1].Set(&x)         // (1,0)
	table[2].Mul(&x, &xFrob) // (1,1)

	z.SetOne()

	for i := 380 - 1; i >= 0; i-- {
		z.Square(z)

		limb := i / 64
		bit := uint(i % 64)
		b0 := (e0[limb] >> bit) & 1
		b1 := (e1[limb] >> bit) & 1

		idx := b0<<1 | b1
		if idx != 0 {
			z.Mul(z, &table[idx-1])
		}
	}

	return z
}
