// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package ip381

// nSquare sets z to x^(2^n) by repeated squaring, returning z.
func (z *Element) nSquare(x *Element, n int) *Element {
	z.Square(x)
	for i := 1; i < n; i++ {
		z.Square(z)
	}
	return z
}

// ExpBySqrtPp1o4 is equivalent to z.Exp(x, 6d400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000).
// It raises x to the (p+1)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPp1o4(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_11      = 1 + _10
	//	_101     = _10 + _11
	//	_1010    = 2*_101
	//	_1101    = _11 + _1010
	//	_1101000 = _1101 << 3
	//	_1101101 = _101 + _1101000
	//	return     (_1101101 << 2 + 1) << 370
	//
	// Operations: 377 squares 5 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
	)

	// var t0,t1 Element
	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t0 = x^0x3
	t0.Mul(&x, z)

	// Step 3: z = x^0x5
	z.Mul(z, t0)

	// Step 4: t1 = x^0xa
	t1.Square(z)

	// Step 5: t0 = x^0xd
	t0.Mul(t0, t1)

	// Step 8: t0 = x^0x68
	t0.nSquare(t0, 3)

	// Step 9: z = x^0x6d
	z.Mul(z, t0)

	// Step 11: z = x^0x1b4
	z.nSquare(z, 2)

	// Step 12: z = x^0x1b5
	z.Mul(&x, z)

	// Step 382: z = x^0x6d400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	z.nSquare(z, 370)

	return z
}

// ExpBySqrtPm3o4 is equivalent to z.Exp(x, 6d3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff).
// It raises x to the (p-3)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPm3o4(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_11      = 1 + _10
	//	_101     = _10 + _11
	//	_1010    = 2*_101
	//	_1111    = _101 + _1010
	//	_10010   = _11 + _1111
	//	_10111   = _101 + _10010
	//	_1011100 = _10111 << 2
	//	i11      = _1011100 << 2
	//	i17      = (_1011100 + i11) << 3 + i11 + _10111
	//	i31      = (i17 << 2 + _1011100) << 9 + i17 + _11
	//	i32      = _10111 + i31
	//	i33      = _10010 + i32
	//	i34      = i31 + i33
	//	i38      = 2*(2*i34 + i34) + i33
	//	i39      = i32 + i38
	//	x27      = i34 + i39
	//	i43      = 2*x27 + x27 + i39
	//	i44      = i38 + i43
	//	i48      = i44 << 2 + i44 + i43
	//	x32      = i44 + i48
	//	i147     = ((i48 << 32 + x32) << 32 + x32) << 32
	//	i214     = ((x32 + i147) << 32 + x32) << 32 + x32
	//	i312     = ((i214 << 32 + x32) << 32 + x32) << 32
	//	i379     = ((x32 + i312) << 32 + x32) << 32 + x32
	//	return     i379 << 27 + x27
	//
	// Operations: 372 squares 35 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
		t3 = new(Element)
		t4 = new(Element)
	)

	// var t0,t1,t2,t3,t4 Element
	// Step 1: t0 = x^0x2
	t0.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, t0)

	// Step 3: t1 = x^0x5
	t1.Mul(t0, z)

	// Step 4: t0 = x^0xa
	t0.Square(t1)

	// Step 5: t0 = x^0xf
	t0.Mul(t1, t0)

	// Step 6: t0 = x^0x12
	t0.Mul(z, t0)

	// Step 7: t1 = x^0x17
	t1.Mul(t1, t0)

	// Step 9: t3 = x^0x5c
	t3.Square(t1)
	t3.Square(t3)

	// Step 11: t2 = x^0x170
	t2.Square(t3)
	t2.Square(t2)

	// Step 12: t4 = x^0x1cc
	t4.Mul(t3, t2)

	// Step 15: t4 = x^0xe60
	t4.nSquare(t4, 3)

	// Step 16: t2 = x^0xfd0
	t2.Mul(t2, t4)

	// Step 17: t2 = x^0xfe7
	t2.Mul(t1, t2)

	// Step 19: t4 = x^0x3f9c
	t4.Square(t2)
	t4.Square(t4)

	// Step 20: t3 = x^0x3ff8
	t3.Mul(t3, t4)

	// Step 29: t3 = x^0x7ff000
	t3.nSquare(t3, 9)

	// Step 30: t2 = x^0x7fffe7
	t2.Mul(t2, t3)

	// Step 31: z = x^0x7fffea
	z.Mul(z, t2)

	// Step 32: t1 = x^0x800001
	t1.Mul(t1, z)

	// Step 33: t0 = x^0x800013
	t0.Mul(t0, t1)

	// Step 34: z = x^0xfffffd
	z.Mul(z, t0)

	// Step 35: t2 = x^0x1fffffa
	t2.Square(z)

	// Step 36: t2 = x^0x2fffff7
	t2.Mul(z, t2)

	// Step 37: t2 = x^0x5ffffee
	t2.Square(t2)

	// Step 38: t0 = x^0x6800001
	t0.Mul(t0, t2)

	// Step 39: t1 = x^0x7000002
	t1.Mul(t1, t0)

	// Step 40: z = x^0x7ffffff
	z.Mul(z, t1)

	// Step 41: t2 = x^0xffffffe
	t2.Square(z)

	// Step 42: t2 = x^0x17fffffd
	t2.Mul(z, t2)

	// Step 43: t1 = x^0x1effffff
	t1.Mul(t1, t2)

	// Step 44: t0 = x^0x25800000
	t0.Mul(t0, t1)

	// Step 46: t2 = x^0x96000000
	t2.Square(t0)
	t2.Square(t2)

	// Step 47: t2 = x^0xbb800000
	t2.Mul(t0, t2)

	// Step 48: t1 = x^0xda7fffff
	t1.Mul(t1, t2)

	// Step 49: t0 = x^0xffffffff
	t0.Mul(t0, t1)

	// Step 81: t1 = x^0xda7fffff00000000
	t1.nSquare(t1, 32)

	// Step 82: t1 = x^0xda7fffffffffffff
	t1.Mul(t0, t1)

	// Step 114: t1 = x^0xda7fffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 115: t1 = x^0xda7fffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 147: t1 = x^0xda7fffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 148: t1 = x^0xda7fffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 180: t1 = x^0xda7fffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 181: t1 = x^0xda7fffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 213: t1 = x^0xda7fffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 214: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 246: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 247: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 279: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 280: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 312: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 313: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 345: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 346: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t1.Mul(t0, t1)

	// Step 378: t1 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000
	t1.nSquare(t1, 32)

	// Step 379: t0 = x^0xda7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(t0, t1)

	// Step 406: t0 = x^0x6d3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8000000
	t0.nSquare(t0, 27)

	// Step 407: z = x^0x6d3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, t0)

	return z
}

// ExpByCbrt2QPlus1Div9 is equivalent to z.Exp(x, 611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7).
// It raises x to the (2q+1)/9 power using a shorter addition chain.
// This is used when q ≡ 4 (mod 9) for efficient cube root computation.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrt2QPlus1Div9(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_110      = 2*_11
	//	_111      = 1 + _110
	//	_1110     = 2*_111
	//	_10101    = _111 + _1110
	//	_10110    = 1 + _10101
	//	_101100   = 2*_10110
	//	_1000010  = _10110 + _101100
	//	_10000100 = 2*_1000010
	//	_10110000 = _101100 + _10000100
	//	_11110010 = _1000010 + _10110000
	//	i21       = (2*_11110010 + _11110010 + _10110000) << 5 + _11110010
	//	i22       = _10101 + i21
	//	i30       = i22 << 7 + _11
	//	i32       = 2*i30 + _10110
	//	i33       = _111 + i32
	//	i34       = i30 + i33
	//	i35       = i33 + i34
	//	i37       = 2*i35 + i34
	//	i38       = i35 + i37
	//	i39       = i32 + i38
	//	i40       = i37 + i39
	//	i43       = 2*i40 + i40 + i38
	//	i44       = i40 + i43
	//	i46       = 2*i44 + i39
	//	i48       = 2*(i43 + i46)
	//	i49       = i44 + i48
	//	i151      = ((i48 << 34 + i49) << 31 + i46) << 35
	//	i220      = ((i49 + i151) << 31 + i46) << 35 + i49
	//	i319      = ((i220 << 31 + i46) << 35 + i49) << 31
	//	i388      = ((i46 + i319) << 35 + i49) << 31 + i46
	//	return      i388 << 18 + i22
	//
	// Operations: 370 squares 37 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
		t3 = new(Element)
		t4 = new(Element)
		t5 = new(Element)
	)

	// var t0,t1,t2,t3,t4,t5 Element
	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t1 = x^0x3
	t1.Mul(&x, z)

	// Step 3: z = x^0x6
	z.Square(t1)

	// Step 4: t2 = x^0x7
	t2.Mul(&x, z)

	// Step 5: z = x^0xe
	z.Square(t2)

	// Step 6: z = x^0x15
	z.Mul(t2, z)

	// Step 7: t0 = x^0x16
	t0.Mul(&x, z)

	// Step 8: t4 = x^0x2c
	t4.Square(t0)

	// Step 9: t3 = x^0x42
	t3.Mul(t0, t4)

	// Step 10: t5 = x^0x84
	t5.Square(t3)

	// Step 11: t4 = x^0xb0
	t4.Mul(t4, t5)

	// Step 12: t3 = x^0xf2
	t3.Mul(t3, t4)

	// Step 13: t5 = x^0x1e4
	t5.Square(t3)

	// Step 14: t5 = x^0x2d6
	t5.Mul(t3, t5)

	// Step 15: t4 = x^0x386
	t4.Mul(t4, t5)

	// Step 20: t4 = x^0x70c0
	t4.nSquare(t4, 5)

	// Step 21: t3 = x^0x71b2
	t3.Mul(t3, t4)

	// Step 22: z = x^0x71c7
	z.Mul(z, t3)

	// Step 29: t3 = x^0x38e380
	t3.Square(z)
	t3.nSquare(t3, 6)

	// Step 30: t1 = x^0x38e383
	t1.Mul(t1, t3)

	// Step 31: t3 = x^0x71c706
	t3.Square(t1)

	// Step 32: t0 = x^0x71c71c
	t0.Mul(t0, t3)

	// Step 33: t2 = x^0x71c723
	t2.Mul(t2, t0)

	// Step 34: t1 = x^0xaaaaa6
	t1.Mul(t1, t2)

	// Step 35: t2 = x^0x11c71c9
	t2.Mul(t2, t1)

	// Step 36: t3 = x^0x238e392
	t3.Square(t2)

	// Step 37: t1 = x^0x2e38e38
	t1.Mul(t1, t3)

	// Step 38: t2 = x^0x4000001
	t2.Mul(t2, t1)

	// Step 39: t0 = x^0x471c71d
	t0.Mul(t0, t2)

	// Step 40: t1 = x^0x7555555
	t1.Mul(t1, t0)

	// Step 41: t3 = x^0xeaaaaaa
	t3.Square(t1)

	// Step 42: t3 = x^0x15ffffff
	t3.Mul(t1, t3)

	// Step 43: t2 = x^0x1a000000
	t2.Mul(t2, t3)

	// Step 44: t1 = x^0x21555555
	t1.Mul(t1, t2)

	// Step 45: t3 = x^0x42aaaaaa
	t3.Square(t1)

	// Step 46: t0 = x^0x471c71c7
	t0.Mul(t0, t3)

	// Step 47: t2 = x^0x611c71c7
	t2.Mul(t2, t0)

	// Step 48: t2 = x^0xc238e38e
	t2.Square(t2)

	// Step 49: t1 = x^0xe38e38e3
	t1.Mul(t1, t2)

	// Step 83: t2 = x^0x308e38e3800000000
	t2.nSquare(t2, 34)

	// Step 84: t2 = x^0x308e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 115: t2 = x^0x18471c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 116: t2 = x^0x18471c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 151: t2 = x^0xc238e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 152: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 183: t2 = x^0x611c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 184: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 219: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 220: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 251: t2 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 252: t2 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 287: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 288: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 319: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 320: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 355: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 356: t1 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t1.Mul(t1, t2)

	// Step 387: t1 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t1.nSquare(t1, 31)

	// Step 388: t0 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t0.Mul(t0, t1)

	// Step 406: t0 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c0000
	t0.nSquare(t0, 18)

	// Step 407: z = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	z.Mul(z, t0)

	return z
}

// ExpByCbrtHelperQMinus4Div9 is equivalent to z.Exp(x, 308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3).
// It raises x to the (q-4)/9 power using an addition chain.
// This helper is used by cbrtAndNormInverse to share exponentiation between
// cube root and norm inverse computations.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrtHelperQMinus4Div9(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_100      = 2*_10
	//	_10000    = _100 << 2
	//	_10010    = _10 + _10000
	//	_100010   = _10000 + _10010
	//	_100011   = 1 + _100010
	//	_110101   = _10010 + _100011
	//	_1010111  = _100010 + _110101
	//	_10001100 = _110101 + _1010111
	//	_11100011 = _1010111 + _10001100
	//	i18       = _11100011 << 6 + _100011
	//	i27       = i18 << 8 + _10001100
	//	i28       = 1 + i27
	//	i29       = i27 + i28
	//	i32       = 2*(_100 + i29) + 1
	//	i33       = i29 + i32
	//	i34       = i32 + i33
	//	i37       = 2*(i33 + i34) + 1
	//	i38       = i34 + i37
	//	i39       = i28 + i38
	//	i40       = i37 + i39
	//	i41       = i38 + i40
	//	i44       = 2*(i39 + i41) + 1
	//	i45       = i41 + i44
	//	i46       = i40 + i45
	//	i47       = 2*i45
	//	i49       = 2*i46 + 1
	//	i151      = ((i47 << 34 + i49) << 31 + i44) << 35
	//	i220      = ((i49 + i151) << 31 + i44) << 35 + i49
	//	i319      = ((i220 << 31 + i44) << 35 + i49) << 31
	//	i388      = ((i44 + i319) << 35 + i49) << 31 + i44
	//	return      i388 << 17 + i18
	//
	// Operations: 369 squares 37 multiplies

	// Allocate Temporaries.
	var (
		t0 = new(Element)
		t1 = new(Element)
		t2 = new(Element)
	)

	// var t0,t1,t2 Element
	// Step 1: t0 = x^0x2
	t0.Square(&x)

	// Step 2: t2 = x^0x4
	t2.Square(t0)

	// Step 4: z = x^0x10
	z.Square(t2)
	z.Square(z)

	// Step 5: t0 = x^0x12
	t0.Mul(t0, z)

	// Step 6: t1 = x^0x22
	t1.Mul(z, t0)

	// Step 7: z = x^0x23
	z.Mul(&x, t1)

	// Step 8: t0 = x^0x35
	t0.Mul(t0, z)

	// Step 9: t1 = x^0x57
	t1.Mul(t1, t0)

	// Step 10: t0 = x^0x8c
	t0.Mul(t0, t1)

	// Step 11: t1 = x^0xe3
	t1.Mul(t1, t0)

	// Step 17: t1 = x^0x38c0
	t1.nSquare(t1, 6)

	// Step 18: z = x^0x38e3
	z.Mul(z, t1)

	// Step 26: t1 = x^0x38e300
	t1.Square(z)
	t1.nSquare(t1, 7)

	// Step 27: t1 = x^0x38e38c
	t1.Mul(t0, t1)

	// Step 28: t0 = x^0x38e38d
	t0.Mul(&x, t1)

	// Step 29: t1 = x^0x71c719
	t1.Mul(t1, t0)

	// Step 30: t2 = x^0x71c71d
	t2.Mul(t2, t1)

	// Step 31: t2 = x^0xe38e3a
	t2.Square(t2)

	// Step 32: t2 = x^0xe38e3b
	t2.Mul(&x, t2)

	// Step 33: t1 = x^0x1555554
	t1.Mul(t1, t2)

	// Step 34: t2 = x^0x238e38f
	t2.Mul(t2, t1)

	// Step 35: t1 = x^0x38e38e3
	t1.Mul(t1, t2)

	// Step 36: t1 = x^0x71c71c6
	t1.Square(t1)

	// Step 37: t1 = x^0x71c71c7
	t1.Mul(&x, t1)

	// Step 38: t2 = x^0x9555556
	t2.Mul(t2, t1)

	// Step 39: t0 = x^0x98e38e3
	t0.Mul(t0, t2)

	// Step 40: t1 = x^0x10aaaaaa
	t1.Mul(t1, t0)

	// Step 41: t2 = x^0x1a000000
	t2.Mul(t2, t1)

	// Step 42: t0 = x^0x238e38e3
	t0.Mul(t0, t2)

	// Step 43: t0 = x^0x471c71c6
	t0.Square(t0)

	// Step 44: t0 = x^0x471c71c7
	t0.Mul(&x, t0)

	// Step 45: t2 = x^0x611c71c7
	t2.Mul(t2, t0)

	// Step 46: t1 = x^0x71c71c71
	t1.Mul(t1, t2)

	// Step 47: t2 = x^0xc238e38e
	t2.Square(t2)

	// Step 48: t1 = x^0xe38e38e2
	t1.Square(t1)

	// Step 49: t1 = x^0xe38e38e3
	t1.Mul(&x, t1)

	// Step 83: t2 = x^0x308e38e3800000000
	t2.nSquare(t2, 34)

	// Step 84: t2 = x^0x308e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 115: t2 = x^0x18471c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 116: t2 = x^0x18471c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 151: t2 = x^0xc238e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 152: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 183: t2 = x^0x611c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 184: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 219: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 220: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 251: t2 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 252: t2 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 287: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 288: t2 = x^0xc238e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t2.Mul(t1, t2)

	// Step 319: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t2.nSquare(t2, 31)

	// Step 320: t2 = x^0x611c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t2.Mul(t0, t2)

	// Step 355: t2 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3800000000
	t2.nSquare(t2, 35)

	// Step 356: t1 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	t1.Mul(t1, t2)

	// Step 387: t1 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7180000000
	t1.nSquare(t1, 31)

	// Step 388: t0 = x^0x18471c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t0.Mul(t0, t1)

	// Step 405: t0 = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e0000
	t0.nSquare(t0, 17)

	// Step 406: z = x^0x308e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e3
	z.Mul(z, t0)

	return z
}
